Repository BIDMCDigitalPsychiatry/LAMP-cortex, pull requests merged in 2022-03, with the labels that each got.

#96 Fixing entropy
  cortex/secondary/entropy.py
Labels: bug

#98 Fixing survey stuff
  cortex/primary/survey_scores.py
  cortex/secondary/survey_results.py
Labels: bug

#100 adding healthkit sleep
  cortex/raw/sleep.py
  cortex/secondary/healthkit_sleep_duration.py
  cortex/secondary/sleep_duration.py
  cortex/secondary/survey_results.py
Labels: feature

#99 Add gap threshold
  cortex/secondary/inactive_duration.py
Labels: feature

#102 Adding question-wise scoring
  cortex/primary/survey_scores.py
  cortex/secondary/survey_results.py
Labels: enhancement

#103 Updating game scoring
  cortex/feature_types.py
  cortex/primary/game_level_scores.py
  cortex/primary/survey_scores.py
  cortex/raw/balloon_risk.py
  cortex/raw/cats_and_dogs.py
  cortex/raw/jewels_a.py
  cortex/raw/jewels_b.py
  cortex/raw/pop_the_bubbles.py
  cortex/raw/spatial_span.py
  cortex/secondary/game_results.py
  cortex/secondary/survey_results.py
  run_pylint.sh
Labels: feature
